### ISSUE TITLE
No module named 'gpio4.GPIO'

### ISSUE THREAD

**Issue by nox0x1** [hankso/gpio4#3]
Installed gpio4 using "python3 -m pip install gpio4" on OpenWrt.
While importing- gpio4.GPIO as GPIO, the following error occurs:

```
Traceback (most recent call last):
  File "/usr/pycode/lcd.py", line 38, in <module>
    import gpio4.GPIO as GPIO
ModuleNotFoundError: No module named 'gpio4.GPIO'
```

**Comment by i0466lt** [comment]
Same here on ASUS Tinkerboard. Any solution?

**Comment by RobertAByrnes** [comment]
Same here on Banana Pi M64

**Comment by evandene** [comment]
Same here on the Banana Pi M2 Zero
 Armbian 22.11.0-trunk Bullseye

Installation:
pi@clearview:~$ sudo pip install gpio4
Looking in indexes: https://pypi.org/simple, https://www.piwheels.org/simple/
Requirement already satisfied: gpio4 in /usr/local/lib/python3.9/dist-packages (0.1.4)
WARNING: Running pip as the 'root' user can result in broken permissions and conflicting behaviour with the system package manager. It is recommended to use a virtual environment instead: https://pip.pypa.io/warnings/venv

**Running a python script:**
pi@clearview:~$ sudo python3 motion_on_off2a.py
Traceback (most recent call last):
  File "/home/pi/motion_on_off2a.py", line 2, in <module>
    import gpio4.GPIO as GPIO
ModuleNotFoundError: No module named 'gpio4.GPIO'

**Comment by evandene** [comment]
After a fresh Armbian 22.11.0-trunk Bullseye installation and:
sudo **python3 pip install gpio4,** the installation is completed.

_Question:_
Where can I find the BCM pin numbers from the BPI M2 Zero? I was trying the pin numbers according the BCM column from the BPI M2 Zero wiki website but that was resulting in errors. See below

pi@clearview:~$ sudo python3 motion_on_off2a.py
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/dist-packages/gpio4/__init__.py", line 393, in                              _get_pin_num
    p = self._mode[pin]
KeyError: 2

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/pi/motion_on_off2a.py", line 30, in <module>
    GPIO.setup([2, 67], GPIO.IN)
  File "/usr/local/lib/python3.9/dist-packages/gpio4/__init__.py", line 424, in  setup
    pins = [self._get_pin_num(p) for p in self._listify(pin)]
  File "/usr/local/lib/python3.9/dist-packages/gpio4/__init__.py", line 424, in  <listcomp>
    pins = [self._get_pin_num(p) for p in self._listify(pin)]
  File "/usr/local/lib/python3.9/dist-packages/gpio4/__init__.py", line 395, in get_pin_num
    raise KeyError(('Invalid pin({}) or unsupported mode!\n'
KeyError: 'Invalid pin(2) or unsupported mode!\nReset mode and check pin num.'

**Comment by GrozaRobotov** [comment]
For me works `from gpio4 import GPIO`
